### ISSUE TITLE
انتقال به dotnet Standard

### ISSUE THREAD

**Issue by OmidRafiee** [unosbaghaie/SmsIrRestfulApi#1]
با سلام 
در صورت امکان به پکیج
 dot net  Standard
.بروز کنید

**Comment by mahdiseilsepour** [comment]
با سلام و احترام
من هم همین درخواست رو دارم در صورت امکان.
با تشکر

**Comment by unosbaghaie** [comment]
سلام 
بله در اولین فرصت ارائه میشه

**Comment by unosbaghaie** [comment]
.net core 2.1 [nuget package ](https://www.nuget.org/packages/SmsIrRestfulNetCore/)is added
