### ISSUE TITLE
Net Standard Package Install Error 

### ISSUE THREAD

**Issue by MAliM1988** [unosbaghaie/SmsIrRestfulApi#2]
سلام 

در موقع نصب پکیج مربوط به Net Core خطای زیر رو دریافت می کنم

SmsIrRestfulNetCore 1.1.4 is not compatible with netstandard2.0 (.NETStandard,Version=v2.0). Package SmsIrRestfulNetCore 1.1.4 supports: netcoreapp2.0 (.NETCoreApp,Version=v2.0)

شما پروژه اتون رو روی Net Core 2.0 پورت کردید ولی Net Standard رو ساپورت نمیکنه که باعث خطای بالا میشه

**Comment by unosbaghaie** [comment]
سلام 
بله netcoreapp2.0 رو فقط ساپورت می کنه . می تونید خودتون سورس رو دانلود کنید و با netstandard2.0 کامپایل و استفاده کنید

**Comment by MAliM1988** [comment]
من پروژه تون رو به Net Standard تغییر دادم ممنون میشم ری  ورژن برای nuget بزنید

[SmsIrRestfulNetStandard.zip](https://github.com/unosbaghaie/SmsIrRestfulApi/files/2708386/SmsIrRestfulNetStandard.zip)

**Comment by unosbaghaie** [comment]
[SmsIrRestfulNetStandard](https://www.nuget.org/packages/SmsIrRestfulNetStandard)

**Comment by MAliM1988** [comment]
ممنون از شما
